#!/bin/bash

# Email Template Image Upload Helper
# This script helps you upload the logo and icon images to your server

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "        📸 EMAIL TEMPLATE - IMAGE UPLOAD HELPER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "You need to upload these 2 images to your server:"
echo ""
echo "📁 Image Files Required:"
echo "   1. GalaDevs Corp Logo navy.png → galadevs-logo-navy.png"
echo "   2. Cafenance.png → cafenance-icon.png"
echo ""
echo "🌐 Upload Location:"
echo "   https://galadevs.com/images/"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 UPLOAD METHODS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Option 1: FTP/SFTP Upload"
echo "  • Use FileZilla or any FTP client"
echo "  • Connect to galadevs.com"
echo "  • Navigate to: /public_html/images/"
echo "  • Upload both PNG files"
echo ""
echo "Option 2: cPanel File Manager"
echo "  • Login to cPanel at https://galadevs.com/cpanel"
echo "  • Go to: File Manager"
echo "  • Navigate to: public_html/images/"
echo "  • Click 'Upload' and select both images"
echo ""
echo "Option 3: Using SCP (if you have SSH access)"
echo "  • Run these commands:"
echo ""
echo "    scp 'GalaDevs Corp Logo navy.png' user@galadevs.com:/path/to/public_html/images/galadevs-logo-navy.png"
echo "    scp 'Cafenance.png' user@galadevs.com:/path/to/public_html/images/cafenance-icon.png"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ VERIFICATION STEPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After uploading, verify the images are accessible:"
echo ""
echo "  Test URLs:"
echo "  • https://galadevs.com/images/galadevs-logo-navy.png"
echo "  • https://galadevs.com/images/cafenance-icon.png"
echo ""
echo "Run these commands to check:"
echo ""

# Check if images exist locally
if [ -f "GalaDevs Corp Logo navy.png" ]; then
    echo "  ✅ Found: GalaDevs Corp Logo navy.png"
else
    echo "  ⚠️  Not found: GalaDevs Corp Logo navy.png"
    echo "     Please ensure the image is in the current directory"
fi

if [ -f "Cafenance.png" ]; then
    echo "  ✅ Found: Cafenance.png"
else
    echo "  ⚠️  Not found: Cafenance.png"
    echo "     Please ensure the image is in the current directory"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 TEST AFTER UPLOAD"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run these commands to verify upload:"
echo ""
echo "  curl -I https://galadevs.com/images/galadevs-logo-navy.png"
echo "  curl -I https://galadevs.com/images/cafenance-icon.png"
echo ""
echo "You should see 'HTTP/2 200' for both"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📧 NEXT STEPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Upload the images using one of the methods above"
echo "2. Verify images are accessible via the test URLs"
echo "3. Upload email template to Supabase Dashboard:"
echo "   → Authentication → Email Templates → Confirm signup"
echo "4. Test by creating a new user account"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
