// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsgs_kFeTnes2yHKl3_EbOuusPtbLOepU',
    appId: '1:863696894678:web:931803c2ba5e0911c8a777',
    messagingSenderId: '863696894678',
    projectId: 'caffeenance-d0958',
    authDomain: 'caffeenance-d0958.firebaseapp.com',
    storageBucket: 'caffeenance-d0958.firebasestorage.app',
    measurementId: 'G-SX3X7W7QST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDahS9nSTA8Q9LPEy6CxLhqCPkuDU-Tjyc',
    appId: '1:863696894678:android:145ba1a95b8316dec8a777',
    messagingSenderId: '863696894678',
    projectId: 'caffeenance-d0958',
    storageBucket: 'caffeenance-d0958.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAois8ZPV5dRvhloo5A73NEtFdrTXKuKO0',
    appId: '1:863696894678:ios:12b9f9114cd9a9c4c8a777',
    messagingSenderId: '863696894678',
    projectId: 'caffeenance-d0958',
    storageBucket: 'caffeenance-d0958.firebasestorage.app',
    iosBundleId: 'com.example.coffeeflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAois8ZPV5dRvhloo5A73NEtFdrTXKuKO0',
    appId: '1:863696894678:ios:12b9f9114cd9a9c4c8a777',
    messagingSenderId: '863696894678',
    projectId: 'caffeenance-d0958',
    storageBucket: 'caffeenance-d0958.firebasestorage.app',
    iosBundleId: 'com.example.coffeeflow',
  );

}